- name: Deploy Scientific Calculator Container
  hosts: localhost
  become: yes
  tasks:

    - name: Pull the latest Docker image
      docker_image:
        name: vaibhav48/scientific-calculator
        source: pull

    - name: Stop and remove existing container (if running)
      docker_container:
        name: scientific_calculator
        state: absent

    - name: Run the new Docker container
      docker_container:
        name: scientific_calculator
        image: vaibhav48/scientific-calculator
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
